version: '3'
services:
  app:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    depends_on:
      - postgres


  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres
    ports:
      - 5433:5433
    env_file:
      - .env
    volumes:
      - ./postgres_data_test:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - .env
    depends_on:
      - postgres